# lightning.pytorch==2.2.1
seed_everything: 42
trainer:
  precision: bf16-mixed
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
  max_epochs: 3
  accumulate_grad_batches: 32
data:
  class_path: lightning_ir.LightningIRDataModule
  init_args:
    num_workers: 4
    train_batch_size: 1
    shuffle_train: true
    inference_batch_size: 4
    train_dataset:
      class_path: lightning_ir.data.dataset.RunDataset
      init_args:
        run_path: __rankzephyr-colbert-10000-sampled-100__msmarco-passage-train-judged.run
        targets: rank
        depth: 100
        sample_size: 100
        sampling_strategy: top
model:
  class_path: lightning_ir.cross_encoder.mono.MonoElectraModule
  init_args:
    model_name_or_path: google/electra-base-discriminator
    config:
      class_path: lightning_ir.MonoElectraConfig
      init_args:
        query_length: 32
        doc_length: 256
    loss_functions:
      - class_path: lightning_ir.RankNet
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.0e-05
