# lightning.pytorch==2.2.1
seed_everything: 42
trainer:
  precision: bf16-mixed
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
  max_steps: 20000
  accumulate_grad_batches: 2
data:
  class_path: lightning_ir.LightningIRDataModule
  init_args:
    num_workers: 4
    train_batch_size: 16
    shuffle_train: true
    inference_batch_size: 4
    train_dataset:
      class_path: lightning_ir.data.dataset.RunDataset
      init_args:
        run_path: __colbert__msmarco-passage-train-judged.run
        targets: relevance
        depth: 200
        sample_size: 8
        sampling_strategy: single_relevant
model:
  class_path: lightning_ir.cross_encoder.mono.MonoElectraModule
  init_args:
    model: null
    model_name_or_path: google/electra-base-discriminator
    config:
      class_path: lightning_ir.MonoElectraConfig
      init_args:
        query_length: 32
        doc_length: 256
    loss_functions:
      - class_path: lightning_ir.LocalizedContrastiveEstimation
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    lr: 1.0e-05
