seed_everything: 42
trainer:
  # precision: 16-mixed
  logger: false
  callbacks:
    - class_path: ReRankCallback
      init_args:
        save_dir: ./runs
data:
  class_path: LightningIRDataModule
  init_args:
    inference_batch_size: 4
    inference_datasets:
      - data/__bm25__msmarco-passage-trec-dl-2019-judged.run
      - data/__bm25__msmarco-passage-trec-dl-2020-judged.run
      - data/__colbert__msmarco-passage-trec-dl-2019-judged.run
      - data/__colbert__msmarco-passage-trec-dl-2020-judged.run
    inference_dataset_config:
      class_path: RunDatasetConfig
      init_args:
        depth: 100
        sample_size: 100
        sampling_strategy: top
model:
  class_path: MonoElectraModule
  init_args:
    model_name_or_path: webis/monoelectra-base
    # model_name_or_path: webis/monoelectra-large
return_predictions: null
