seed_everything: 42
trainer:
  # precision: 16-mixed
  logger: false
  callbacks:
    - class_path: ReRankCallback
      init_args:
        save_dir: ./runs
data:
  class_path: LightningIRDataModule
  init_args:
    inference_batch_size: 4
    inference_datasets:
      - class_path: RunDataset
        init_args:
          run_path: data/__bm25__msmarco-passage-trec-dl-2019-judged.run
          depth: 100
          sample_size: 100
          sampling_strategy: top
      - class_path: RunDataset
        init_args:
          run_path: data/__bm25__msmarco-passage-trec-dl-2020-judged.run
          depth: 100
          sample_size: 100
          sampling_strategy: top
      - class_path: RunDataset
        init_args:
          run_path: data/__colbert__msmarco-passage-trec-dl-2019-judged.run
          depth: 100
          sample_size: 100
          sampling_strategy: top
      - class_path: RunDataset
        init_args:
          run_path: data/__colbert__msmarco-passage-trec-dl-2020-judged.run
          depth: 100
          sample_size: 100
          sampling_strategy: top
model:
  class_path: MonoElectraModule
  init_args:
    model_name_or_path: path_to_model
return_predictions: null
